### ISSUE TITLE
Use of g++ instead of gcc for compiling cpp programs

### ISSUE THREAD

**Issue by bkhanale** [vibhor1997a/compile-run#1]
I think `g++` must be used instead of `gcc` to compile the cpp programs. Also the current error system does not provide any use for the debugging process.

**Comment by vibhor1997a** [comment]
`g++` inlcudes `libstdc++` in linking which is not included in `gcc` by default but we are explicitly specifying the `-lstdc++` option to include it in the linking process. So, basically its no different than using `gcc`. 
You can refer https://stackoverflow.com/questions/172587/what-is-the-difference-between-g-and-gcc and https://stackoverflow.com/questions/5759353/is-g-both-a-c-compiler-and-a-linker 

And also this library is not meant to handle debugging. Its basically meant to execute your programs without a hassle and give you the `stderr` and `stdout`.

**Comment by bkhanale** [comment]
Okay, got it. But on including `#include <bits/stdc++.h>` returns nothing at stdout and stderr.

**Comment by vibhor1997a** [comment]
It might be due to the timeout of the compilation process as this file imports many headers which would have been resulting in higher compilation time . Default timeout for compilation is `3 seconds`. So you can increase it maybe try setting it to `7-8` seconds by passing value in milliseconds in the `compileTimeout` option.
